#Picture
pic:
  x_scale: 19
  y_scale: 22
  x: 40
  y: 10

#أسم حامل الوثيقة (بالأفرانجي)
vorname:
  x: 50
  y: 40
  
  #محل الميلاد
visaArt:
  x: 65
  y: 30
  
#تاريخ الميلاد
visaValid:
  x: 30
  y: 30
  
  #المهنة
profession:
  x: 30
  y: 20

#اسم ألام
duration:
  x: 30
  y: 10

#أأقرب الأقارب بليبيا
work:
  x: 30
  y: 0

#أسباب التواجد
entriesNumber:
  x: 30
  y: -10

#العنوان
port:
  x: 30
  y: -20
  
  #الرقم الوطني
passport:
  x: 30
  y: -30

#الرقم التسجيل
visaNumber:
  x: 140
  y: 80

#أسباب صرف الوثيقة
note:
  x: 150
  y: 30

#"تاريخ إصدار الوثيقة
visaIss:
  x: 130
  y: 10
  
#Place of Iss
entryFee:
  x: 120
  y: 0
#أسم حامل الوثيقة (بالعربي)
nachname:
  x: 180
  y: -30

