#Picture
pic:
  x_scale: 25
  y_scale: 35
  x: 24
  y: 9

#أسم حامل الوثيقة (بالأفرانجي)
vorname:
  x: 60
  y: 36
   
#تاريخ الميلاد
visaValid:
  x: 49
  y: 26
  
 #محل الميلاد
visaArt:
  x: 52
  y: 21
  #المهنة
profession:
  x: 38
  y: 18

#اسم ألام
duration:
  x: 40
  y: 9

#أأقرب الأقارب بليبيا
work:
  x: 30
  y: 0

#أسباب التواجد
entriesNumber:
  x: 35
  y: -9

#العنوان
port:
  x: 32
  y: -18
  
  #الرقم الوطني
passport:
  x: 33
  y: -27

#الرقم التسجيل
visaNumber:
  x: 130
  y: 82

#أسباب صرف الوثيقة
note:
  x: 160
  y: 36

#"تاريخ إصدار الوثيقة
visaIss:
  x: 137
  y: 11
  
#Place of Iss
entryFee:
  x: 137
  y: 4
#أسم حامل الوثيقة (بالعربي)
nachname:
  x: 175
  y: -25

